services:
  llm02:
    build: .
    container_name: 'llm02'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    working_dir: '/root/'
    tty: true
    volumes:
      - ./gihyo-langchain-search:/root/gihyo-langchain-search
      - ./node_modules:/root/node_modules
    ports:
      - 127.0.0.1:8503:8503
